In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

notebooks_folder = Path.cwd()
raw_folder = notebooks_folder.parent / "data" / "raw"
processed_folder = notebooks_folder.parent / "data" / "processed"

In [2]:
datasets = {
    "aum_by_fund_house": "aum_by_fund_house.csv",
    "benchmark_indices": "benchmark_indices.csv",
    "category_inflows": "category_inflows.csv",
    "fund_master": "fund_master.csv",
    "industry_folio_count": "industry_folio_count.csv",
    "investor_transactions": "investor_transactions.csv",
    "monthly_sip_inflows": "monthly_sip_inflows.csv",
    "nav_history": "nav_history.csv",
    "portfolio_holdings": "portfolio_holdings.csv",
    "scheme_performance": "scheme_performance.csv"
}

In [3]:
dataframes = {}

for name, file in datasets.items():
    df = pd.read_csv(raw_folder / file)
    dataframes[name] = df

In [4]:
for name, df in dataframes.items():
    print(f"DATASET: {name.upper()}")
    print("="*80)

    print("\nShape:")
    print(df.shape)

    print("\nData Types:")
    print(df.dtypes)

    print("\nFirst 5 Rows:")
    display(df.head())

DATASET: AUM_BY_FUND_HOUSE
================================================================================

Shape:
(90, 5)

Data Types:
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

First 5 Rows:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  31-03-2022      SBI Mutual Fund            6.05     605000          186
1  31-03-2022  ICICI Prudential MF            4.65     465000          216
2  31-03-2022     HDFC Mutual Fund            4.35     435000          195
3  31-03-2022      Nippon India MF            2.70     270000          177
4  31-03-2022    Kotak Mahindra MF            2.70     270000          168

DATASET: BENCHMARK_INDICES
================================================================================

Shape:
(8050, 3)

Data Types:
date               str
index_name         str
close_value    float64
dtype: object

First 5 Rows:

         date index_name  close_value
0  03-01-2022    NIFTY50     17492.79
1  04-01-2022    NIFTY50     17689.64
2  05-01-2022    NIFTY50     17835.05
3  06-01-2022    NIFTY50     17878.51
4  07-01-2022    NIFTY50     17759.15

DATASET: CATEGORY_INFLOWS
================================================================================

Shape:
(144, 3)

Data Types:
month                 str
category              str
net_inflow_crore    int64
dtype: object

First 5 Rows:

     month         category  net_inflow_crore
0  2024-04        Large Cap              2413
1  2024-04          Mid Cap              3897
2  2024-04        Small Cap              3533
3  2024-04        Flexi Cap              4947
4  2024-04  Large & Mid Cap              4214

DATASET: FUND_MASTER
================================================================================

Shape:
(40, 15)

Data Types:
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

First 5 Rows:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,14-02-2006,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,01-01-2013,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,09-09-2009,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,01-01-2013,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,30-12-2000,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

DATASET: INDUSTRY_FOLIO_COUNT
================================================================================

Shape:
(21, 6)

Data Types:
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

First 5 Rows:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

DATASET: INVESTOR_TRANSACTIONS
================================================================================

Shape:
(32778, 13)

Data Types:
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

First 5 Rows:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,01-01-2024,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,01-01-2024,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,01-01-2024,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,01-01-2024,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,01-01-2024,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

DATASET: MONTHLY_SIP_INFLOWS
================================================================================

Shape:
(48, 6)

Data Types:
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

First 5 Rows:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

DATASET: NAV_HISTORY
================================================================================

Shape:
(46000, 3)

Data Types:
amfi_code      int64
date             str
nav          float64
dtype: object

First 5 Rows:

   amfi_code        date      nav
0     119551  03-01-2022  54.3856
1     119551  04-01-2022  54.3474
2     119551  05-01-2022  54.6869
3     119551  06-01-2022  55.4550
4     119551  07-01-2022  55.3692

DATASET: PORTFOLIO_HOLDINGS
================================================================================

Shape:
(322, 8)

Data Types:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

First 5 Rows:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,31-12-2025
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,31-12-2025
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,31-12-2025
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,31-12-2025
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,31-12-2025

DATASET: SCHEME_PERFORMANCE
================================================================================

Shape:
(40, 19)

Data Types:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

First 5 Rows:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [5]:
for name, df in dataframes.items():
    print(f"MISSING VALUES - {name.upper()}")
    missing = df.isnull().sum()
    print("The number of missing values are ",missing)

MISSING VALUES - AUM_BY_FUND_HOUSE
The number of missing values are  date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64
MISSING VALUES - BENCHMARK_INDICES
The number of missing values are  date           0
index_name     0
close_value    0
dtype: int64
MISSING VALUES - CATEGORY_INFLOWS
The number of missing values are  month               0
category            0
net_inflow_crore    0
dtype: int64
MISSING VALUES - FUND_MASTER
The number of missing values are  amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64
MISSING VALUES - INDUSTRY_FOLIO_COUNT
The number of missing values are  month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64
MISSING VALUES - INVESTOR_TRANSACTIONS
The number of missing values are  investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64
MISSING VALUES - MONTHLY_SIP_INFLOWS
The number of missing values are  month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64
MISSING VALUES - NAV_HISTORY
The number of missing values are  amfi_code    0
date         0
nav          0
dtype: int64
MISSING VALUES - PORTFOLIO_HOLDINGS
The number of missing values are  amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64
MISSING VALUES - SCHEME_PERFORMANCE
The number of missing values are  amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [6]:
for name, df in dataframes.items():
    duplicates = df.duplicated().sum()
    print(f"{name}: {duplicates} duplicate rows")

aum_by_fund_house: 0 duplicate rows
benchmark_indices: 0 duplicate rows
category_inflows: 0 duplicate rows
fund_master: 0 duplicate rows
industry_folio_count: 0 duplicate rows
investor_transactions: 0 duplicate rows
monthly_sip_inflows: 0 duplicate rows
nav_history: 0 duplicate rows
portfolio_holdings: 0 duplicate rows
scheme_performance: 0 duplicate rows

In [7]:
quality_report = []

for name, df in dataframes.items():
    quality_report.append({
        "dataset": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "missing_values": int(df.isnull().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum())
    })

quality_df = pd.DataFrame(quality_report)

display(quality_df)

                 dataset   rows  columns  missing_values  duplicate_rows
0      aum_by_fund_house     90        5               0               0
1      benchmark_indices   8050        3               0               0
2       category_inflows    144        3               0               0
3            fund_master     40       15               0               0
4   industry_folio_count     21        6               0               0
5  investor_transactions  32778       13               0               0
6    monthly_sip_inflows     48        6              12               0
7            nav_history  46000        3               0               0
8     portfolio_holdings    322        8               0               0
9     scheme_performance     40       19               0               0

In [8]:
fund_master = dataframes["fund_master"]

print("Total Schemes:", len(fund_master))
print()

print("Unique Fund Houses:")
print(fund_master["fund_house"].nunique())
print(fund_master["fund_house"].sort_values().unique())

print("\nUnique Categories:")
print(fund_master["category"].unique())

print("\nUnique Sub Categories:")
print(fund_master["sub_category"].unique())

print("\nUnique Risk Categories:")
print(fund_master["risk_category"].unique())

print("\nSEBI Category Codes:")
print(fund_master["sebi_category_code"].unique())

Total Schemes: 40

Unique Fund Houses:
10
<StringArray>
['Aditya Birla Sun Life MF',         'Axis Mutual Fund',
          'DSP Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',        'Kotak Mahindra MF',
           'Mirae Asset MF',          'Nippon India MF',
          'SBI Mutual Fund',          'UTI Mutual Fund']
Length: 10, dtype: str

Unique Categories:
<StringArray>
['Equity', 'Debt']
Length: 2, dtype: str

Unique Sub Categories:
<StringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

Unique Risk Categories:
<StringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

SEBI Category Codes:
<StringArray>
['EC01', 'EC03', 'DC02', 'EC02', 'EC06', 'DC01', 'EI01', 'EC04', 'EC05']
Length: 9, dtype: str

In [9]:
print("AMFI Code Summary")

print("\nMin Code:")
print(fund_master["amfi_code"].min())

print("\nMax Code:")
print(fund_master["amfi_code"].max())

print("\nSample Codes:")
print(fund_master["amfi_code"].head(20).tolist())

AMFI Code Summary

Min Code:
100016

Max Code:
149324

Sample Codes:
[119551, 119552, 119598, 119599, 119120, 100016, 125497, 100033, 125498, 100025, 120503, 120504, 120505, 120506, 120507, 118632, 118633, 118634, 118635, 118636]

In [10]:
fund_master_codes = set(
    dataframes["fund_master"]["amfi_code"].astype(str)
)

nav_codes = set(
    dataframes["nav_history"]["amfi_code"].astype(str)
)

missing_in_nav = fund_master_codes - nav_codes

print("Fund Master Codes:", len(fund_master_codes))
print("NAV History Codes:", len(nav_codes))
print("Missing Codes:", len(missing_in_nav))

Fund Master Codes: 40
NAV History Codes: 40
Missing Codes: 0

In [11]:
missing_df = pd.DataFrame({
    "missing_amfi_code": list(missing_in_nav)
})

display(missing_df.head(20))

Empty DataFrame
Columns: [missing_amfi_code]
Index: []

In [12]:
print("DATA QUALITY SUMMARY")

total_codes = len(fund_master_codes)
matched_codes = total_codes - len(missing_in_nav)

coverage_pct = round((matched_codes / total_codes) * 100,2)

print(f"Total Fund Master AMFI Codes : {total_codes}")
print(f"Codes Found In NAV History   : {matched_codes}")
print(f"Missing Codes                : {len(missing_in_nav)}")
print(f"Coverage %                   : {coverage_pct}%")

if len(missing_in_nav) == 0:
    print("\nAll AMFI codes are available in NAV history.")
else:
    print(f"\n {len(missing_in_nav)} AMFI codes are missing from NAV history.")

DATA QUALITY SUMMARY
Total Fund Master AMFI Codes : 40
Codes Found In NAV History   : 40
Missing Codes                : 0
Coverage %                   : 100.0%

All AMFI codes are available in NAV history.